//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Contact</summary>
	[PublishedContentModel("contact")]
	public partial class Contact : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contact";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Contact(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Contact, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Label "Email address"
		///</summary>
		[ImplementPropertyType("labelEmailAddress")]
		public string LabelEmailAddress
		{
			get { return this.GetPropertyValue<string>("labelEmailAddress"); }
		}

		///<summary>
		/// Label "Message"
		///</summary>
		[ImplementPropertyType("labelMessage")]
		public string LabelMessage
		{
			get { return this.GetPropertyValue<string>("labelMessage"); }
		}

		///<summary>
		/// Label "Name"
		///</summary>
		[ImplementPropertyType("labelName")]
		public string LabelName
		{
			get { return this.GetPropertyValue<string>("labelName"); }
		}

		///<summary>
		/// Minimum amount of times to use word
		///</summary>
		[ImplementPropertyType("minimumAmountOfTimesToUseWord")]
		public int MinimumAmountOfTimesToUseWord
		{
			get { return this.GetPropertyValue<int>("minimumAmountOfTimesToUseWord"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Word to use in message
		///</summary>
		[ImplementPropertyType("wordToUseInMessage")]
		public string WordToUseInMessage
		{
			get { return this.GetPropertyValue<string>("wordToUseInMessage"); }
		}
	}
}
