//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Settings</summary>
	[PublishedContentModel("settings")]
	public partial class Settings : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Settings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Settings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email address invalid
		///</summary>
		[ImplementPropertyType("emailAddressInvalid")]
		public string EmailAddressInvalid
		{
			get { return this.GetPropertyValue<string>("emailAddressInvalid"); }
		}

		///<summary>
		/// Field length exceeded
		///</summary>
		[ImplementPropertyType("fieldLengthExceeded")]
		public string FieldLengthExceeded
		{
			get { return this.GetPropertyValue<string>("fieldLengthExceeded"); }
		}

		///<summary>
		/// Required field
		///</summary>
		[ImplementPropertyType("requiredField")]
		public string RequiredField
		{
			get { return this.GetPropertyValue<string>("requiredField"); }
		}

		///<summary>
		/// Word not used N times
		///</summary>
		[ImplementPropertyType("wordNotUsedNTimes")]
		public string WordNotUsedNtimes
		{
			get { return this.GetPropertyValue<string>("wordNotUsedNTimes"); }
		}
	}
}
